/* tslint:disable */
/* eslint-disable */
/**
 * Dehydrated API
 * Authentication is optional and depends on server configuration. When enabled, all API endpoints require a valid JWT token in the Authorization header. When disabled, no authentication is required.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelDomainEntry } from "./ModelDomainEntry";
import {
  ModelDomainEntryFromJSON,
  ModelDomainEntryFromJSONTyped,
  ModelDomainEntryToJSON,
  ModelDomainEntryToJSONTyped,
} from "./ModelDomainEntry";

/**
 * Response containing multiple domain entries
 * @export
 * @interface ModelDomainsResponse
 */
export interface ModelDomainsResponse {
  /**
   * Data contains the list of domain entries if the operation was successful.
   * @Description List of domain entries if the operation was successful
   * @type {Array<ModelDomainEntry>}
   * @memberof ModelDomainsResponse
   */
  data?: Array<ModelDomainEntry>;
  /**
   * Error contains an error message if the operation failed.
   * @Description Error message if the operation failed
   * @type {string}
   * @memberof ModelDomainsResponse
   */
  error?: string;
  /**
   * Success indicates whether the operation was successful.
   * @Description Whether the operation was successful
   * @type {boolean}
   * @memberof ModelDomainsResponse
   */
  success?: boolean;
}

/**
 * Check if a given object implements the ModelDomainsResponse interface.
 */
export function instanceOfModelDomainsResponse(
  value: object,
): value is ModelDomainsResponse {
  return true;
}

export function ModelDomainsResponseFromJSON(json: any): ModelDomainsResponse {
  return ModelDomainsResponseFromJSONTyped(json, false);
}

export function ModelDomainsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelDomainsResponse {
  if (json == null) {
    return json;
  }
  return {
    data:
      json["data"] == null
        ? undefined
        : (json["data"] as Array<any>).map(ModelDomainEntryFromJSON),
    error: json["error"] == null ? undefined : json["error"],
    success: json["success"] == null ? undefined : json["success"],
  };
}

export function ModelDomainsResponseToJSON(json: any): ModelDomainsResponse {
  return ModelDomainsResponseToJSONTyped(json, false);
}

export function ModelDomainsResponseToJSONTyped(
  value?: ModelDomainsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data:
      value["data"] == null
        ? undefined
        : (value["data"] as Array<any>).map(ModelDomainEntryToJSON),
    error: value["error"],
    success: value["success"],
  };
}
