/* tslint:disable */
/* eslint-disable */
/**
 * Dehydrated API
 * Authentication is optional and depends on server configuration. When enabled, all API endpoints require a valid JWT token in the Authorization header. When disabled, no authentication is required.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelDomainEntry } from './ModelDomainEntry';
import {
    ModelDomainEntryFromJSON,
    ModelDomainEntryFromJSONTyped,
    ModelDomainEntryToJSON,
    ModelDomainEntryToJSONTyped,
} from './ModelDomainEntry';

/**
 * Response containing a single domain entry
 * @export
 * @interface ModelDomainResponse
 */
export interface ModelDomainResponse {
    /**
     * Data contains the domain entry if the operation was successful.
     * @Description Domain entry data if the operation was successful
     * @type {ModelDomainEntry}
     * @memberof ModelDomainResponse
     */
    data?: ModelDomainEntry;
    /**
     * Error contains an error message if the operation failed.
     * @Description Error message if the operation failed
     * @type {string}
     * @memberof ModelDomainResponse
     */
    error?: string;
    /**
     * Success indicates whether the operation was successful.
     * @Description Whether the operation was successful
     * @type {boolean}
     * @memberof ModelDomainResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the ModelDomainResponse interface.
 */
export function instanceOfModelDomainResponse(value: object): value is ModelDomainResponse {
    return true;
}

export function ModelDomainResponseFromJSON(json: any): ModelDomainResponse {
    return ModelDomainResponseFromJSONTyped(json, false);
}

export function ModelDomainResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDomainResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ModelDomainEntryFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function ModelDomainResponseToJSON(json: any): ModelDomainResponse {
    return ModelDomainResponseToJSONTyped(json, false);
}

export function ModelDomainResponseToJSONTyped(value?: ModelDomainResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ModelDomainEntryToJSON(value['data']),
        'error': value['error'],
        'success': value['success'],
    };
}

