/* tslint:disable */
/* eslint-disable */
/**
 * Dehydrated API
 * Authentication is optional and depends on server configuration. When enabled, all API endpoints require a valid JWT token in the Authorization header. When disabled, no authentication is required.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to delete an existing domain entry
 * @export
 * @interface ModelDeleteDomainRequest
 */
export interface ModelDeleteDomainRequest {
    /**
     * Alias is an optional alternative identifier.
     * @Description Optional alternative identifier for the domain
     * @type {string}
     * @memberof ModelDeleteDomainRequest
     */
    alias?: string;
}

/**
 * Check if a given object implements the ModelDeleteDomainRequest interface.
 */
export function instanceOfModelDeleteDomainRequest(value: object): value is ModelDeleteDomainRequest {
    return true;
}

export function ModelDeleteDomainRequestFromJSON(json: any): ModelDeleteDomainRequest {
    return ModelDeleteDomainRequestFromJSONTyped(json, false);
}

export function ModelDeleteDomainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDeleteDomainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'] == null ? undefined : json['alias'],
    };
}

export function ModelDeleteDomainRequestToJSON(json: any): ModelDeleteDomainRequest {
    return ModelDeleteDomainRequestToJSONTyped(json, false);
}

export function ModelDeleteDomainRequestToJSONTyped(value?: ModelDeleteDomainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
    };
}

