apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dehydrated-frontend

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: dehydrated-frontend
  version: v1.0.0

images:
- name: dehydrated-frontend
  newTag: latest 