#!/bin/sh
set -e

cat <<EOF > /usr/share/nginx/html/env-config.js
window.ENV_CONFIG = {
    VITE_APP_BASE_URI: "${VITE_APP_BASE_URI}",
    VITE_API_BASE_URL: "${VITE_API_BASE_URL}",
    VITE_ENABLE_MSAL: "${VITE_ENABLE_MSAL}",
    VITE_THEME_NAME: "${VITE_THEME_NAME}",
    VITE_THEME_MODE: "${VITE_THEME_MODE}",
    VITE_MSAL_CLIENT_ID: "${VITE_MSAL_CLIENT_ID}",
    VITE_MSAL_AUTHORITY: "${VITE_MSAL_AUTHORITY}",
    VITE_DEHYDRATED_API_IDENTIFIER: "${VITE_DEHYDRATED_API_IDENTIFIER}"
};
EOF 