apiVersion: apps/v1
kind: Deployment
metadata:
  name: dehydrated-frontend
  labels:
    app: dehydrated-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dehydrated-frontend
  template:
    metadata:
      labels:
        app: dehydrated-frontend
    spec:
      containers:
      - name: dehydrated-frontend
        image: registrypro.hanse-merkur.de/iti-si/terraform-projects/netscaler/dehydrated-frontend:v0.1.0
        ports:
        - containerPort: 80
        env:
        - name: VITE_APP_BASE_URI
          valueFrom:
            configMapKeyRef:
              name: dehydrated-frontend-config
              key: VITE_APP_BASE_URI
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: dehydrated-frontend-config
              key: VITE_API_BASE_URL
        - name: VITE_ENABLE_MSAL
          valueFrom:
            configMapKeyRef:
              name: dehydrated-frontend-config
              key: VITE_ENABLE_MSAL
        - name: VITE_THEME_NAME
          valueFrom:
            configMapKeyRef:
              name: dehydrated-frontend-config
              key: VITE_THEME_NAME
        - name: VITE_THEME_MODE
          valueFrom:
            configMapKeyRef:
              name: dehydrated-frontend-config
              key: VITE_THEME_MODE
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: dehydrated-frontend-config
              key: NODE_ENV
        # MSAL configuration (only used when VITE_ENABLE_MSAL=true)
        - name: VITE_MSAL_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dehydrated-frontend-msal-secret
              key: VITE_MSAL_CLIENT_ID
              optional: true
        - name: VITE_MSAL_AUTHORITY
          valueFrom:
            secretKeyRef:
              name: dehydrated-frontend-msal-secret
              key: VITE_MSAL_AUTHORITY
              optional: true
        - name: VITE_DEHYDRATED_API_IDENTIFIER
          valueFrom:
            secretKeyRef:
              name: dehydrated-frontend-msal-secret
              key: VITE_DEHYDRATED_API_IDENTIFIER
              optional: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 101 