apiVersion: v1
kind: Service
metadata:
  name: dehydrated-frontend-service
  labels:
    app: dehydrated-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dehydrated-frontend 